### ISSUE TITLE
Regarding use for backups

### ISSUE THREAD

**Issue by jeffrson** [ezbz/gitlabber#41]
Not really a bug, but some questions:
I want to use gitlabber for backing up my repositories from Gitlab.

How does gitlabber behave then? Should I simply rerun it? Will it clone new repositories and update (fetch) existing?

Is there a "mirror mode" (`git clone --mirror` ; `git remote update`)?

Thanks a lot

**Comment by ezbz** [comment]
If the project directory exists and is a valid git repository (has `.git` folder in it) gitlabber will perform a git pull in the directory, otherwise the project directory will be created and the gitlab project will be cloned into it.

Currently mirror mode is not supported, gitlabber also doesn't backup any GitLab server constructs there are other tools to do that.

**Comment by lambdafu** [comment]
Would be good to have a way to use "git clone --bare" to save disk space.
